### ISSUE TITLE
Chance of Error in Data Generator

### ISSUE THREAD

**Issue by tomzhu1024** [CarnegieMellon-PlantD/PlantD-operator#25]
When running the data generator with the following Schema and DataSet definitions (from [plantd-test-pipeline](https://github.com/CarnegieMellon-PlantD/plantd-test-pipeline)):

```
apiVersion: windtunnel.plantd.org/v1alpha1
kind: Schema
metadata:
  labels:
    app.kubernetes.io/name: schema
    app.kubernetes.io/instance: schema
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd-operator
  name:  product
  namespace: test-pipeline
spec:
  columns:
  - name: product_id
    type: uuid
  - name: product_name
    type: beername
  - name: quantity
    type: number
    params:
      min: "10"
      max: "50"
---
apiVersion: windtunnel.plantd.org/v1alpha1
kind: Schema
metadata:
  labels:
    app.kubernetes.io/name: schema
    app.kubernetes.io/instance: schema
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd-operator
  name:  supplier
  namespace: test-pipeline
spec:
  columns:
  - name: supplier_id
    type: uuid
  - name: supplier_name
    type: company
  - name: product_id
    type: uuid
    formula:
      name: Copy
      args: ["product.product_id"]
  - name: supplies_available
    type: number
    params:
      min: "100"
      max: "500"
---
apiVersion: windtunnel.plantd.org/v1alpha1
kind: Schema
metadata:
  labels:
    app.kubernetes.io/name: schema
    app.kubernetes.io/instance: schema
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd-operator
  name:  warehouse
  namespace: test-pipeline
spec:
  columns:
  - name: warehouse_id
    type: uuid
  - name: warehouse_name
    type: company
  - name: supplier_id
    type: uuid
    formula:
      name: Copy
      args: ["supplier.supplier_id"]
  - name: product_id
    type: uuid
    formula:
      name: Copy
      args: ["product.product_id"]
  - name: total_availability
    type: number
    params:
      min: "100"
      max: "500"
```

```
apiVersion: windtunnel.plantd.org/v1alpha1
kind: DataSet
metadata:
  labels:
    app.kubernetes.io/name: dataset
    app.kubernetes.io/instance: dataset
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd-operator
  name: dataset-test-pipeline
  namespace: test-pipeline
spec:
  # the file format of the each file containing the generated data 
  # this may or may not be the output file format based on whether you want to compress these files
  fileFormat: "csv"
  # the file format for the compressed files 
  # each file inside the compressed file is of "fileFormat" format specified above
  # this is the output format if specified for the files
  compressedFileFormat: "zip"
  # if you wish files from all the different schemas to compressed into one compressed file leave this field as false
  # if you wish to have a different compressed file for every schema, mark this field as true
  compressPerSchema: false
  # the total number of output files irrespective of compression
  # unless "compressPerSchema" is false, this field is applicable per schema
  numFiles: 100
  parallelJobs: 1
  schemas:
    - name: product
      # the number of records to be generated in each output file
      # a random number is picked from the specified range
      numRecords:
        min: 1
        max: 3
      # the number of intermediate files to be compressed into a single compressed file
      # a random number is picked from the specified range
      numFilesPerCompressedFile:
        min: 1
        max: 1
    - name: supplier
      numRecords:
        min: 1
        max: 3
      numFilesPerCompressedFile:
        min: 1
        max: 1
    - name: warehouse
      numRecords:
        min: 1
        max: 3
      numFilesPerCompressedFile:
        min: 1
        max: 1
```

There is a chance of getting the following error:

```
Error: Failed to get sample dataset: Out of index: supplier.supplier_id
```
